create table public.object_types (
    id int primary key generated by default as identity not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    ptres int not null,
    name text not null
);

alter table if exists public.object_types enable row level security;

create policy "Enable read for authenticated users only"
on public.object_types for select
to authenticated
using (
    true
);

create trigger set_oject_types_updated_at
before update on public.object_types
for each row
execute function set_updated_at();